# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zbBC6uDpfcsTy8IvJhpPsUDF42XV3djY
"""

def kassalik_tashxisi( alomat):
  if alomat==" qorin og'riq":
    return " espuizam"
  elif alomat=="istima":
    return "kupen"
  elif alomat=="tish og'riq":
    return "bolnol"
  elif alomat==" tomoq og'riq ":
    return"anzibel"
  elif alomat=="bel og'riq":
    return "kupen maz"
  elif alomat=="teri kassalikgi":
    return " kojinni"
  elif alomat=="bosh og'riq":
    return "parastemol"
  elif alomat=="apendiz":
    return"zudlik bn aperatsiya"
  elif alomat=="yurak og'riq":
    return"valirinka"
  elif alomat=="boyin og'riq":
    return "dalgit krem"
  else:
    return "Noaniq kassalik, SHifokorga murojat qiling"

natija=kasalomat=input("Alomat kiriting")salik_tashxisi(alomat)
print(natija)

def tarjimon( matn):
 if alomat==" olma":
   return"ЯАБлока"
 elif alomat=="anor":
   return "гранат"
 elif alomat=="shaftoli":
   return "персик"
 elif alomat=="malina":
    return "вишня"
 elif alomat=="mandarin":
    return "манго"
 else:
   return "Noaniq kassalik, SHifokorga murojat qiling"
matn=input("matnni kiriting ")
natija=tarjimon(matn)
print(natija)